[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "numeric-array"
description = "Wrapper around generic-array that adds efficient numeric trait implementations"
repository = "https://github.com/novacrazy/numeric-array"
documentation = "https://docs.rs/numeric-array"
version = "0.4.2"
readme = "README.md"
keywords = ["generic", "array", "numeric", "simd"]
include = ["src/**/*", "Cargo.toml"]
license = "MIT"
categories = ["data-structures"]

[dependencies]
generic-array = "0.13"
num-traits = { version = "0.2.10", default_features = false }
typenum = "1.10"
serde = { version = "1.0.85", optional = true, default_features = false }

[features]
serde1 = ["serde", "generic-array/serde"]

[dev-dependencies]
serde_json = "1.0.37"
