[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
name = "numeric-array"
description = "Wrapper around generic-array that adds efficient numeric trait implementations"
repository = "https://github.com/novacrazy/numeric-array"
documentation = "https://docs.rs/numeric-array"
version = "0.3.0"
readme = "README.md"
keywords = ["generic", "array", "numeric", "simd"]
include = ["src/**/*", "Cargo.toml"]
license = "MIT"
categories = ["data-structures"]

[dependencies]
generic-array = "0.12"
num-traits = "0.2.2"
typenum = "1.10"
